### ISSUE TITLE
Integrate into components

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-material-styles#49]
needs #48

- Create a separate `vaadin-material-styles` repo. (or use this one?) and include common theme styles
- Create a script that copies the element styles under `themes/material` of each element and updates dependencies etc
  - Commit to a separate feature branch "md-preview"
  - Modify README to include instructions on how to import the Material version instead of the default one

**Comment by platosha** [comment]
https://gist.github.com/platosha/fb46360c0deca6aa737c9f77df9f8807

**Comment by tomivirkki** [comment]
Apply the theme in P3-supported format right away so don't need a second conversion for that later. Here's the new structure https://github.com/vaadin/vaadin-button/tree/p3-preview/theme/lumo

**Comment by tomivirkki** [comment]
Before migrating, branch the current master revisions as "vaadin-10" as agreed in https://github.com/vaadin/components-team-tasks/issues/368

**Comment by manolo** [comment]
I used this script instead of @platosha because was pretty easier to me deal with bash than node

https://gist.github.com/manolo/61de2e1f08f17e994fc84106408623fe
