### ISSUE TITLE
Plan the UX tests

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-material-styles#51]
child of #48

**Comment by tomivirkki** [comment]
Updated the UX app "material" branch to use the master version of Vaadin material theme

**Comment by manolo** [comment]
Plan Document:

https://docs.google.com/document/d/16TyKkDGSz2xqVnTh-RgX7E8sHPpgnk8ZKZejBaPQRYE/edit#heading=h.298hseaqagxl
