### ISSUE TITLE
Roboto font is not used in the demo on IE11

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-material-styles#58]
The default font stack is used instead. Something is not working correctly with the polyfills.

![screen shot 2018-05-29 at 12 56 03](https://user-images.githubusercontent.com/66382/40652266-7b9f64a2-6340-11e8-8e3b-dfdab93d3119.png)

If you add the following to `demo/common.html` directly, the font is used correctly:

```html
  <custom-style>
    <style>
      body {
        font-family: var(--material-font-family);
      }
    </style>
  </custom-style>
``` 
For some reason `<style include="material-typography">` doesn’t work correctly.

**Comment by Haprog** [comment]
Seems to affect also Edge.

**Comment by Haprog** [comment]
This seems to be because this line (in `typography.html`):
```html
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" crossorigin="anonymous">
```
Is not working in Edge and IE11.

Seems to be fixed by just adding `type="text/css"` to it. Will commit a fix.
