### ISSUE TITLE
Notification Color is not OK on iOS

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-material-styles#60]
`<h3>` content is not shown with enough contrast

![captura de pantalla 2018-06-06 a las 12 01 28](https://user-images.githubusercontent.com/161853/41028107-5bc9043e-6981-11e8-9dc5-32ad54831645.png)

It might be a problem in the app (check that typography and colors modules are included in the app)

**Comment by jouni** [comment]
I suspect that the Lumo color.html is somehow imported and [this style module include](https://github.com/vaadin/vaadin-core-elements-ux/blob/material/src/vaadin-core-elements-ux-app/form-test.html#L25) works and sets the color for the header element. So it would be working as expected.

**Comment by jouni** [comment]
Closing this as no-one else has reported this issue. I assume this was an issue in the test setup, that somehow both Lumo and Material styles were imported and included on the same page.
