### ISSUE TITLE
External dependency might cause slow page load/errors

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-material-styles#77]
It took me a while to catch this, but debugging a slow page load I've found the cause to be this line in `typography.html`:

```
<!-- Import Roboto from Google Fonts -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" crossorigin="anonymous">
```

If a Vaadin app is used without Internet access or behind a captive portal, an external dependency like this might slow down page load or even throw errors.

P.S. I'm not even using `vaadin-material-styles`, but somehow it comes along with other dependencies via Flow webjars.

**Comment by jouni** [comment]
Oh, are we importing that by default in our Material theme? Seems risky. I would avoid that, and leave as an option for the developer.

**Comment by heruan** [comment]
Any update on this? Still causes major trouble for apps without internet access.

**Comment by heruan** [comment]
Still not clear to me why the browser makes that request even if I'm not using the Material theme.

**Comment by web-padawan** [comment]
Yes that's weird. Can you reproduce this without Flow, using web component only?

**Comment by heruan** [comment]
Turns out this is happening only when bundling the Flow app for production: the unused files are loaded from the bundle. In development mode it doesn't happen.

**Comment by pekam** [comment]
Yeah, IIRC the Flow bundler scans for all the `HtmlImports` it finds in the classpath and adds them to the main bundle. So AFAIK the easiest way to exclude a non-used html-file is to exclude the maven dependency that imports it. Maybe it's also possible by [moving the non-used imports into a separate fragment](https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/production/tutorial-production-mode-customising.asciidoc#defining-fragments-with-maven).
