### ISSUE TITLE
Blank screen and JavaScript syntax errors in IE11

### ISSUE THREAD

**Issue by evmatt** [vaadin/vaadin-material-styles#83]
When running a Vaadin application in IE11 the user sees only a blank white screen. The issue only occurs when using the Material theme and does not occur with the Lumo theme. The issue does not occur in browsers other than IE11.

In the IE11 console, 3 errors are seen. All are `SCRIPT5022: SyntaxError` originating in the file style-properties.js at line 30,3. Below is the context, lines 26 to 31.
```
const matchesSelector = function(selector) {
  const method = this.matches || this.matchesSelector ||
    this.mozMatchesSelector || this.msMatchesSelector ||
    this.oMatchesSelector || this.webkitMatchesSelector;
  return method && method.call(this, selector);
};
```

**Comment by web-padawan** [comment]
There should not be `const` in the resulting output, so it looks like at least some code is not transpiled to ES5. Are you running the Vaadin application in production mode?

**Comment by evmatt** [comment]
The Vaadin application is being run in production mode, and the Vaadin version being used is 12.0.0. Other files do appear to be transpiled to ES5 as style-properties.js is the only source file causing problems. `const` appears throughout the whole of style-properties.js so it appears that the whole file is missed during transpilation.

**Comment by web-padawan** [comment]
This issue was moved to vaadin/flow#4944
